name: flutter_package1
description: A new Flutter project.

publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: '>=3.1.2 <4.0.0'


dependencies:
  flutter:
    sdk: flutter



  cupertino_icons: ^1.0.2
  flutter_advanced_drawer: ^1.3.5
  animated_text_kit: ^4.2.2
  url_launcher: ^6.2.2
  awesome_dialog: ^3.1.0
  fluttertoast: ^8.2.4
  google_fonts: ^6.1.0
  logger: ^2.0.2+1

  platform_device_id: ^1.0.1
dev_dependencies:
  flutter_test:


    sdk: flutter


  flutter_lints: ^2.0.0



flutter:


  uses-material-design: true


  assets:
     - assets/

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
